import {
  build_feature_shell_page,
  type KirletPageDecl,
} from "@opus-perpetuus/imperium-core-kit";

const API = "api://m/subject-ventas";

export const purchase_order_pages: KirletPageDecl[] = [
  {
    id: "ventas.purchase-order",
    path: "purchase-order",
    permission: "subject.ventas.purchase-order.read",
    build: () =>
      build_feature_shell_page({
        id: "ventas.purchase-order",
        owner: "subject-ventas",
        title: "Órdenes de compra",
        props: {
          basePath: "purchase-order",
          idKey: "id",
          nameKey: "name",
          view: {
            title: "Órdenes de compra",
            subtitle: "Submenú de ventas",
            pluralLabel: "órdenes de compra",
            singularLabel: "órdenes de compra",
            emptyTitle: "Sin registros",
            emptyDescription: "Migra desde Mongo o crea el primero",
          },
          data: {
            list: `${API}/purchase-order`,
            record: `${API}/purchase-order/:id`,
            create: { method: "POST", action: `${API}/purchase-order` },
            update: { method: "PATCH", action: `${API}/purchase-order/:id` },
            delete: { method: "DELETE", action: `${API}/purchase-order/:id` },
          },
          table: {
            columns: [
              { key: "name", label: "Nombre", sortable: true, priority: 1 },
              { key: "is_active", label: "Activo", sortable: true, priority: 2 },
              { key: "ref", label: "Ref", sortable: true, priority: 3 },
              { key: "folio_interno", label: "folio interno", sortable: true, priority: 3 },
              { key: "proveedor_nombre", label: "proveedor nombre", sortable: true, priority: 3 },
              { key: "proveedor_id", label: "proveedor id", sortable: true, priority: 3 },
              { key: "estado", label: "estado", sortable: true, priority: 3 },
              { key: "tipo_origen", label: "tipo origen", sortable: true, priority: 3 },
              { key: "total_cantidad", label: "total cantidad", sortable: true, priority: 3 },
            ],
            fillHeight: true,
            serverQuery: true,
          },
          form: {
            fields: [
              { name: "name", component: "input-text", label: "Nombre", required: true },
              { name: "description", component: "input-textarea", label: "Descripción" },
              { name: "ref", component: "input-text", label: "Referencia (_ref)" },
              { name: "folio_interno", component: "input-number", label: "folio interno" },
              { name: "proveedor_nombre", component: "input-text", label: "proveedor nombre" },
              { name: "proveedor_id", component: "input-text", label: "proveedor id" },
              {
                name: "estado",
                component: "input-menu",
                label: "estado",
                options: [
                  { value: "borrador", label: "Borrador" },
                  { value: "aprobada", label: "Aprobada" },
                  { value: "parcialmente_recibida", label: "Recepción parcial" },
                  { value: "confirmada", label: "Confirmada" },
                ],
              },
              {
                name: "tipo_origen",
                component: "input-menu",
                label: "tipo origen",
                options: [
                  { value: "manual", label: "Manual" },
                  { value: "xml", label: "XML" },
                ],
              },
              { name: "total_cantidad", component: "input-number", label: "total cantidad" },
              { name: "total_recibido", component: "input-number", label: "total recibido" },
              { name: "subtotal", component: "input-money", label: "subtotal" },
              { name: "fecha_aprobacion", component: "input-date", label: "fecha aprobacion" },
              { name: "fecha_confirmacion", component: "input-date", label: "fecha confirmacion" },
              { name: "producto", component: "input-text", label: "producto" },
              { name: "producto_nombre", component: "input-text", label: "producto nombre" },
              { name: "producto_codigo", component: "input-text", label: "producto codigo" },
              { name: "codigo_proveedor", component: "input-text", label: "codigo proveedor" },
              { name: "descripcion_origen", component: "input-textarea", label: "descripcion origen" },
              { name: "cantidad", component: "input-number", label: "cantidad" },
              { name: "cantidad_recibida", component: "input-number", label: "cantidad recibida" },
              { name: "costo_unitario", component: "input-money", label: "costo unitario" },
              { name: "importe", component: "input-money", label: "importe" },
              { name: "origen_pedido_folio", component: "input-text", label: "origen pedido folio" },
              { name: "cantidad_faltante", component: "input-number", label: "cantidad faltante" },
              { name: "cantidad_sugerida_consumo", component: "input-number", label: "cantidad sugerida consumo" },
              { name: "recepcion_pendiente", component: "input-datalist", label: "recepcion pendiente", optionsSource: "api://m/subject-almacen/inventory-reception?as=options&limite=1000" },
              { name: "recepcion_pendiente_nombre", component: "input-text", label: "recepcion pendiente nombre" },
              { name: "cantidad_desde_recepcion", component: "input-number", label: "cantidad desde recepcion" },
              { name: "costo_total", component: "input-money", label: "costo total" },
              { name: "ubicacion_destino", component: "input-text", label: "ubicacion destino" },
              { name: "ubicacion_destino_nombre", component: "input-text", label: "ubicacion destino nombre" },
              { name: "receipt_key", component: "input-text", label: "receipt key" },
              { name: "referencia", component: "input-text", label: "referencia" },
              { name: "fecha_recepcion", component: "input-date", label: "fecha recepcion" },
              { name: "notas", component: "input-textarea", label: "notas" },
              { name: "articulos", component: "input-json", label: "articulos" },
              { name: "numero_factura", component: "input-text", label: "numero factura" },
              { name: "fecha_factura", component: "input-date", label: "fecha factura" },
              { name: "monto_total", component: "input-money", label: "monto total" },
              { name: "proveedor", component: "input-datalist", label: "proveedor", optionsSource: "api://m/subject-ventas/contacto?as=options&limite=1000" },
              { name: "proveedor_rfc", component: "input-text", label: "proveedor rfc" },
              { name: "referencia_origen", component: "input-text", label: "referencia origen" },
              { name: "uuid_xml", component: "input-text", label: "uuid xml" },
              { name: "aprobado_por", component: "input-text", label: "aprobado por" },
              { name: "aprobado_por_nombre", component: "input-text", label: "aprobado por nombre" },
              { name: "recepciones", component: "input-json", label: "recepciones" },
              { name: "facturas_proveedor", component: "input-json", label: "facturas proveedor" },
            ],
          },
        },
      }),
  },
];
