import type { KirletTableDecl } from "@opus-perpetuus/imperium-core-kit";

export const purchase_order_tables: KirletTableDecl[] = [
  {
    name: "purchase_order",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "name", type: "text", notNull: true },
      { name: "description", type: "text" },
      { name: "is_active", type: "boolean", notNull: true, default: true },
      { name: "state", type: "text" },
      { name: "ref", type: "text", unique: true },
      { name: "search_field", type: "text" },
      { name: "created_by", type: "text" },
      { name: "custom_data", type: "json" },
      { name: "payload", type: "json" },
      { name: "created_at", type: "text", notNull: true },
      { name: "updated_at", type: "text", notNull: true },
      { name: "folio_interno", type: "real" },
      { name: "proveedor_nombre", type: "text" },
      { name: "proveedor_id", type: "text" },
      { name: "estado", type: "text" },
      { name: "tipo_origen", type: "text" },
      { name: "total_cantidad", type: "real" },
      { name: "total_recibido", type: "real" },
      { name: "subtotal", type: "real" },
      { name: "fecha_aprobacion", type: "text" },
      { name: "fecha_confirmacion", type: "text" },
      { name: "producto", type: "text" },
      { name: "producto_nombre", type: "text" },
      { name: "producto_codigo", type: "text" },
      { name: "codigo_proveedor", type: "text" },
      { name: "descripcion_origen", type: "text" },
      { name: "cantidad", type: "real" },
      { name: "cantidad_recibida", type: "real" },
      { name: "costo_unitario", type: "real" },
      { name: "importe", type: "real" },
      { name: "origen_pedido_folio", type: "text" },
      { name: "cantidad_faltante", type: "real" },
      { name: "cantidad_sugerida_consumo", type: "real" },
      { name: "recepcion_pendiente", type: "text" },
      { name: "recepcion_pendiente_nombre", type: "text" },
      { name: "cantidad_desde_recepcion", type: "real" },
      { name: "costo_total", type: "real" },
      { name: "ubicacion_destino", type: "text" },
      { name: "ubicacion_destino_nombre", type: "text" },
      { name: "receipt_key", type: "text" },
      { name: "referencia", type: "text" },
      { name: "fecha_recepcion", type: "text" },
      { name: "notas", type: "text" },
      { name: "articulos", type: "json" },
      { name: "numero_factura", type: "text" },
      { name: "fecha_factura", type: "text" },
      { name: "monto_total", type: "real" },
      { name: "proveedor", type: "text" },
      { name: "proveedor_rfc", type: "text" },
      { name: "referencia_origen", type: "text" },
      { name: "uuid_xml", type: "text" },
      { name: "aprobado_por", type: "text" },
      { name: "aprobado_por_nombre", type: "text" },
      { name: "recepciones", type: "json" },
      { name: "facturas_proveedor", type: "json" },
    ],
    indexes: [
      { name: "idx_purchase_order_name", columns: ["name"] },
      { name: "idx_purchase_order_active", columns: ["is_active"] },
    ],
  },
];
