import { define_crud, define_module } from "@opus-perpetuus/imperium-core-kit";
import { purchase_order_pages } from "./purchase-order.pages.ts";
import { purchase_order_tables } from "./purchase-order.tables.ts";

export const purchase_order_module = define_module({
  resource: "purchase-order",
  labels: {
    singular: "Órdenes de compra",
    plural: "Órdenes de compra",
    read: "Ver Órdenes de compra",
    write: "Editar Órdenes de compra",
  },
  routes: define_crud({
    resource: "purchase-order",
    table: "purchase_order",
    soft_delete: true,
    soft_delete_field: "is_active",
    history: true,
    default_sort: "name:asc",
    id_prefix: "purchase",
    fields: {
      name: { type: "string", required: true, search: true },
      description: { type: "string", search: true },
      is_active: { type: "boolean" },
      state: { type: "string" },
      ref: { type: "string", search: true },
      search_field: { type: "string", search: true },
      created_by: { type: "string" },
      custom_data: { type: "json" },
      payload: { type: "json" },
      folio_interno: { type: "number" },
      proveedor_nombre: { type: "string", search: true },
      proveedor_id: { type: "string", search: true },
      estado: { type: "string", search: true },
      tipo_origen: { type: "string", search: true },
      total_cantidad: { type: "number" },
      total_recibido: { type: "number" },
      subtotal: { type: "number" },
      fecha_aprobacion: { type: "string", search: true },
      fecha_confirmacion: { type: "string", search: true },
      producto: { type: "string", search: true },
      producto_nombre: { type: "string", search: true },
      producto_codigo: { type: "string", search: true },
      codigo_proveedor: { type: "string", search: true },
      descripcion_origen: { type: "string", search: true },
      cantidad: { type: "number" },
      cantidad_recibida: { type: "number" },
      costo_unitario: { type: "number" },
      importe: { type: "number" },
      origen_pedido_folio: { type: "string", search: true },
      cantidad_faltante: { type: "number" },
      cantidad_sugerida_consumo: { type: "number" },
      recepcion_pendiente: { type: "string", search: true },
      recepcion_pendiente_nombre: { type: "string", search: true },
      cantidad_desde_recepcion: { type: "number" },
      costo_total: { type: "number" },
      ubicacion_destino: { type: "string", search: true },
      ubicacion_destino_nombre: { type: "string", search: true },
      receipt_key: { type: "string", search: true },
      referencia: { type: "string", search: true },
      fecha_recepcion: { type: "string", search: true },
      notas: { type: "string", search: true },
      articulos: { type: "json" },
      numero_factura: { type: "string", search: true },
      fecha_factura: { type: "string", search: true },
      monto_total: { type: "number" },
      proveedor: { type: "string", search: true },
      proveedor_rfc: { type: "string", search: true },
      referencia_origen: { type: "string", search: true },
      uuid_xml: { type: "string", search: true },
      aprobado_por: { type: "string", search: true },
      aprobado_por_nombre: { type: "string", search: true },
      recepciones: { type: "json" },
      facturas_proveedor: { type: "json" },
    },
    options_map: { value: "id", label: "name" },
  }),
  tables: purchase_order_tables,
  pages: purchase_order_pages,
  menu: [
    {
      id: "ventas.purchase-order",
      label: "Órdenes de compra",
      order: 0,
      pageId: "ventas.purchase-order",
      path: "purchase-order",
      permission: "subject.ventas.purchase-order.read",
      icon: "document",
    },
    {
      id: "ventas.lista-de-precios",
      label: "Lista de precios",
      order: 0,
      pageId: "ventas.lista-de-precios",
      path: "lista-de-precios",
      permission: "subject.ventas.lista-de-precios.read",
      icon: "document",
    },
    {
      id: "ventas.contacto",
      label: "Contacto",
      order: 0,
      pageId: "ventas.contacto",
      path: "contacto",
      permission: "subject.ventas.contacto.read",
      icon: "document",
    },
    {
      id: "ventas.sku",
      label: "Productos",
      order: 0,
      pageId: "ventas.sku",
      path: "sku",
      permission: "subject.ventas.sku.read",
      icon: "document",
    },
    {
      id: "ventas.invoice-request",
      label: "Solicitudes de facturación",
      order: 1,
      pageId: "ventas.invoice-request",
      path: "invoice-request",
      permission: "subject.ventas.invoice-request.read",
      icon: "document",
    },
    {
      id: "ventas.pedidos",
      label: "Pedidos",
      order: 10,
      pageId: "ventas.pedidos",
      path: "pedidos",
      permission: "subject.ventas.pedidos.read",
      icon: "document",
    },
    {
      id: "ventas.products",
      label: "Productos",
      order: 10,
      pageId: "ventas.products",
      path: "products",
      permission: "subject.ventas.products.read",
      icon: "document",
    }
    ],
});
