import type { KirletTableDecl } from "@opus-perpetuus/imperium-core-kit";

export const contacto_tables: KirletTableDecl[] = [
  {
    name: "contacto",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "name", type: "text", notNull: true },
      { name: "description", type: "text" },
      { name: "is_active", type: "boolean", notNull: true, default: true },
      { name: "state", type: "text" },
      { name: "ref", type: "text", unique: true },
      { name: "search_field", type: "text" },
      { name: "created_by", type: "text" },
      { name: "custom_data", type: "json" },
      { name: "payload", type: "json" },
      { name: "created_at", type: "text", notNull: true },
      { name: "updated_at", type: "text", notNull: true },
      { name: "rfc", type: "text" },
      { name: "esCliente", type: "text" },
      { name: "esProveedor", type: "text" },
      { name: "codigo", type: "text" },
      { name: "rutas", type: "text" },
      { name: "usuariosAsignados", type: "text" },
      { name: "listaDePrecios", type: "text" },
      { name: "facturacion_dividida_habilitada", type: "boolean" },
      { name: "facturacion_dividida_monto_maximo", type: "real" },
      { name: "facturacion_requiere_autorizacion_cobranza", type: "boolean" },
      { name: "nombre_fiscal", type: "text" },
      { name: "regimen_fiscal", type: "text" },
      { name: "uso_cfdi_default", type: "text" },
      { name: "calle", type: "text" },
      { name: "numeroInterior", type: "text" },
      { name: "numeroExterior", type: "text" },
      { name: "colonia", type: "text" },
      { name: "codigoPostal", type: "text" },
      { name: "estado", type: "text" },
      { name: "pais", type: "text" },
      { name: "ciudad", type: "text" },
      { name: "urlMaps", type: "text" },
      { name: "ubicacion", type: "text" },
      { name: "latitude", type: "real" },
      { name: "longitude", type: "real" },
    ],
    indexes: [
      { name: "idx_contacto_name", columns: ["name"] },
      { name: "idx_contacto_active", columns: ["is_active"] },
    ],
  },
];
