import { define_crud, define_module } from "@opus-perpetuus/imperium-core-kit";
import { contacto_pages } from "./contacto.pages.ts";
import { contacto_tables } from "./contacto.tables.ts";

export const contacto_module = define_module({
  resource: "contacto",
  labels: {
    singular: "Contacto",
    plural: "Contacto",
    read: "Ver Contacto",
    write: "Editar Contacto",
  },
  routes: define_crud({
    resource: "contacto",
    table: "contacto",
    soft_delete: true,
    soft_delete_field: "is_active",
    history: true,
    default_sort: "name:asc",
    id_prefix: "contacto",
    fields: {
      name: { type: "string", required: true, search: true },
      description: { type: "string", search: true },
      is_active: { type: "boolean" },
      state: { type: "string" },
      ref: { type: "string", search: true },
      search_field: { type: "string", search: true },
      created_by: { type: "string" },
      custom_data: { type: "json" },
      payload: { type: "json" },
      rfc: { type: "string", search: true },
      esCliente: { type: "string", search: true },
      esProveedor: { type: "string", search: true },
      codigo: { type: "string", search: true },
      rutas: { type: "string", search: true },
      usuariosAsignados: { type: "string", search: true },
      listaDePrecios: { type: "string", search: true },
      facturacion_dividida_habilitada: { type: "boolean" },
      facturacion_dividida_monto_maximo: { type: "number" },
      facturacion_requiere_autorizacion_cobranza: { type: "boolean" },
      nombre_fiscal: { type: "string", search: true },
      regimen_fiscal: { type: "string", search: true },
      uso_cfdi_default: { type: "string", search: true },
      calle: { type: "string", search: true },
      numeroInterior: { type: "string", search: true },
      numeroExterior: { type: "string", search: true },
      colonia: { type: "string", search: true },
      codigoPostal: { type: "string", search: true },
      estado: { type: "string", search: true },
      pais: { type: "string", search: true },
      ciudad: { type: "string", search: true },
      urlMaps: { type: "string", search: true },
      ubicacion: { type: "string", search: true },
      latitude: { type: "number" },
      longitude: { type: "number" },
    },
    options_map: { value: "id", label: "name" },
  }),
  tables: contacto_tables,
  pages: contacto_pages,
  menu: [],
});
