import type { KirletTableDecl } from "@opus-perpetuus/imperium-core-kit";

export const invoice_request_tables: KirletTableDecl[] = [
  {
    name: "invoice_request",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "name", type: "text", notNull: true },
      { name: "description", type: "text" },
      { name: "is_active", type: "boolean", notNull: true, default: true },
      { name: "state", type: "text" },
      { name: "ref", type: "text", unique: true },
      { name: "search_field", type: "text" },
      { name: "created_by", type: "text" },
      { name: "custom_data", type: "json" },
      { name: "payload", type: "json" },
      { name: "created_at", type: "text", notNull: true },
      { name: "updated_at", type: "text", notNull: true },
      { name: "pedido_folio", type: "text" },
      { name: "contacto_nombre", type: "text" },
      { name: "estado", type: "text" },
      { name: "monto_total", type: "real" },
      { name: "monto_umbral", type: "real" },
      { name: "autorizado_cobranza", type: "boolean" },
      { name: "requiere_facturacion_dividida", type: "boolean" },
      { name: "cfdi_document_id", type: "text" },
      { name: "cfdi_document_status", type: "text" },
      { name: "cfdi_document_name", type: "text" },
      { name: "pedido_articulo_index", type: "real" },
      { name: "product_name", type: "text" },
      { name: "cantidad_original", type: "real" },
      { name: "cantidad_facturable", type: "real" },
      { name: "precio_unitario", type: "real" },
      { name: "index", type: "real" },
      { name: "articulos_count", type: "real" },
      { name: "articulos", type: "json" },
      { name: "pedido", type: "text" },
      { name: "pedido_estado", type: "text" },
      { name: "contacto", type: "text" },
      { name: "pedido_total", type: "real" },
      { name: "pedido_iva", type: "real" },
      { name: "base_calculo", type: "text" },
      { name: "requiere_autorizacion_cobranza", type: "boolean" },
      { name: "subpedidos", type: "json" },
    ],
    indexes: [
      { name: "idx_invoice_request_name", columns: ["name"] },
      { name: "idx_invoice_request_active", columns: ["is_active"] },
    ],
  },
];
