import { define_crud, define_module } from "@opus-perpetuus/imperium-core-kit";
import { invoice_request_pages } from "./invoice-request.pages.ts";
import { invoice_request_tables } from "./invoice-request.tables.ts";

export const invoice_request_module = define_module({
  resource: "invoice-request",
  labels: {
    singular: "Solicitudes de facturación",
    plural: "Solicitudes de facturación",
    read: "Ver Solicitudes de facturación",
    write: "Editar Solicitudes de facturación",
  },
  routes: define_crud({
    resource: "invoice-request",
    table: "invoice_request",
    soft_delete: true,
    soft_delete_field: "is_active",
    history: true,
    default_sort: "name:asc",
    id_prefix: "invoice-",
    fields: {
      name: { type: "string", required: true, search: true },
      description: { type: "string", search: true },
      is_active: { type: "boolean" },
      state: { type: "string" },
      ref: { type: "string", search: true },
      search_field: { type: "string", search: true },
      created_by: { type: "string" },
      custom_data: { type: "json" },
      payload: { type: "json" },
      pedido_folio: { type: "string", search: true },
      contacto_nombre: { type: "string", search: true },
      estado: { type: "string", search: true },
      monto_total: { type: "number" },
      monto_umbral: { type: "number" },
      autorizado_cobranza: { type: "boolean" },
      requiere_facturacion_dividida: { type: "boolean" },
      cfdi_document_id: { type: "string", search: true },
      cfdi_document_status: { type: "string", search: true },
      cfdi_document_name: { type: "string", search: true },
      pedido_articulo_index: { type: "number" },
      product_name: { type: "string", search: true },
      cantidad_original: { type: "number" },
      cantidad_facturable: { type: "number" },
      precio_unitario: { type: "number" },
      index: { type: "number" },
      articulos_count: { type: "number" },
      articulos: { type: "json" },
      pedido: { type: "string", search: true },
      pedido_estado: { type: "string", search: true },
      contacto: { type: "string", search: true },
      pedido_total: { type: "number" },
      pedido_iva: { type: "number" },
      base_calculo: { type: "string", search: true },
      requiere_autorizacion_cobranza: { type: "boolean" },
      subpedidos: { type: "json" },
    },
    options_map: { value: "id", label: "name" },
  }),
  tables: invoice_request_tables,
  pages: invoice_request_pages,
  menu: [],
});
