import { define_crud, define_module } from "@opus-perpetuus/imperium-core-kit";
import { products_pages } from "./products.pages.ts";
import { products_tables } from "./products.tables.ts";

export const products_module = define_module({
  resource: "products",
  labels: {
    singular: "Productos",
    plural: "Productos",
    read: "Ver Productos",
    write: "Editar Productos",
  },
  routes: define_crud({
    resource: "products",
    table: "products",
    soft_delete: true,
    soft_delete_field: "is_active",
    history: true,
    default_sort: "name:asc",
    id_prefix: "products",
    fields: {
      name: { type: "string", required: true, search: true },
      description: { type: "string", search: true },
      is_active: { type: "boolean" },
      state: { type: "string" },
      ref: { type: "string", search: true },
      search_field: { type: "string", search: true },
      created_by: { type: "string" },
      custom_data: { type: "json" },
      payload: { type: "json" },
      puedoProducirlo: { type: "boolean" },
      puedoComprarlo: { type: "boolean" },
      puedoVenderlo: { type: "boolean" },
      codigo: { type: "string", search: true },
      positional_code: { type: "string", search: true },
      unidad: { type: "string", search: true },
      descripcion: { type: "string", search: true },
      existencia: { type: "number" },
      existenciaApartada: { type: "number" },
      existenciaDisponible: { type: "string", search: true },
      costoVenta: { type: "number" },
      costoCompraPromedio: { type: "number" },
      ultimoCostoCompra: { type: "number" },
      fechaUltimaCompra: { type: "string", search: true },
      stockMinimo: { type: "number" },
      stockMaximo: { type: "string", search: true },
      etiquetas: { type: "string", search: true },
      image: { type: "string", search: true },
      codigos_proveedor: { type: "string", search: true },
      clave_prod_serv: { type: "string", search: true },
      objeto_imp_default: { type: "string", search: true },
      ubicacion_preferida: { type: "string", search: true },
      ubicacion_preferida_codigo: { type: "string", search: true },
      proveedor: { type: "string", search: true },
      proveedor_nombre: { type: "string", search: true },
    },
    options_map: { value: "id", label: "name" },
  }),
  tables: products_tables,
  pages: products_pages,
  menu: [],
});
