import type { KirletTableDecl } from "@opus-perpetuus/imperium-core-kit";

export const products_tables: KirletTableDecl[] = [
  {
    name: "products",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "name", type: "text", notNull: true },
      { name: "description", type: "text" },
      { name: "is_active", type: "boolean", notNull: true, default: true },
      { name: "state", type: "text" },
      { name: "ref", type: "text", unique: true },
      { name: "search_field", type: "text" },
      { name: "created_by", type: "text" },
      { name: "custom_data", type: "json" },
      { name: "payload", type: "json" },
      { name: "created_at", type: "text", notNull: true },
      { name: "updated_at", type: "text", notNull: true },
      { name: "puedoProducirlo", type: "boolean" },
      { name: "puedoComprarlo", type: "boolean" },
      { name: "puedoVenderlo", type: "boolean" },
      { name: "codigo", type: "text" },
      { name: "positional_code", type: "text" },
      { name: "unidad", type: "text" },
      { name: "descripcion", type: "text" },
      { name: "existencia", type: "real" },
      { name: "existenciaApartada", type: "real" },
      { name: "existenciaDisponible", type: "text" },
      { name: "costoVenta", type: "real" },
      { name: "costoCompraPromedio", type: "real" },
      { name: "ultimoCostoCompra", type: "real" },
      { name: "fechaUltimaCompra", type: "text" },
      { name: "stockMinimo", type: "real" },
      { name: "stockMaximo", type: "text" },
      { name: "etiquetas", type: "text" },
      { name: "image", type: "text" },
      { name: "codigos_proveedor", type: "text" },
      { name: "clave_prod_serv", type: "text" },
      { name: "objeto_imp_default", type: "text" },
      { name: "ubicacion_preferida", type: "text" },
      { name: "ubicacion_preferida_codigo", type: "text" },
      { name: "proveedor", type: "text" },
      { name: "proveedor_nombre", type: "text" },
    ],
    indexes: [
      { name: "idx_products_name", columns: ["name"] },
      { name: "idx_products_active", columns: ["is_active"] },
    ],
  },
];
