import type { KirletTableDecl } from "@opus-perpetuus/imperium-core-kit";

export const pedidos_tables: KirletTableDecl[] = [
  {
    name: "pedidos",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "name", type: "text", notNull: true },
      { name: "description", type: "text" },
      { name: "is_active", type: "boolean", notNull: true, default: true },
      { name: "state", type: "text" },
      { name: "ref", type: "text", unique: true },
      { name: "search_field", type: "text" },
      { name: "created_by", type: "text" },
      { name: "custom_data", type: "json" },
      { name: "payload", type: "json" },
      { name: "created_at", type: "text", notNull: true },
      { name: "updated_at", type: "text", notNull: true },
      { name: "folio_interno", type: "text" },
      { name: "fecha", type: "text" },
      { name: "contacto", type: "text" },
      { name: "contacto_id", type: "text" },
      { name: "usuario", type: "text" },
      { name: "estado", type: "text" },
      { name: "total", type: "text" },
      { name: "iva", type: "text" },
      { name: "importe", type: "real" },
      { name: "folio", type: "text" },
      { name: "assigned_employee", type: "text" },
      { name: "init_time", type: "text" },
      { name: "end_time", type: "text" },
      { name: "sincronizado", type: "boolean" },
      { name: "invoice_request_id", type: "text" },
      { name: "invoice_request_name", type: "text" },
      { name: "invoice_request_estado", type: "text" },
      { name: "invoice_request_monto_total", type: "text" },
      { name: "invoice_request_actualizado", type: "text" },
      { name: "ruta", type: "text" },
      { name: "cantidad", type: "real" },
      { name: "cantidad_surtida", type: "real" },
      { name: "precio", type: "real" },
      { name: "product", type: "text" },
      { name: "price_origin", type: "text" },
      { name: "listaDePreciosId", type: "text" },
      { name: "offline_uuid", type: "text" },
    ],
    indexes: [
      { name: "idx_pedidos_name", columns: ["name"] },
      { name: "idx_pedidos_active", columns: ["is_active"] },
    ],
  },
];
