import { define_crud, define_module } from "@opus-perpetuus/imperium-core-kit";
import { pedidos_pages } from "./pedidos.pages.ts";
import { pedidos_tables } from "./pedidos.tables.ts";

export const pedidos_module = define_module({
  resource: "pedidos",
  labels: {
    singular: "Pedidos",
    plural: "Pedidos",
    read: "Ver Pedidos",
    write: "Editar Pedidos",
  },
  routes: define_crud({
    resource: "pedidos",
    table: "pedidos",
    soft_delete: true,
    soft_delete_field: "is_active",
    history: true,
    default_sort: "name:asc",
    id_prefix: "pedidos",
    fields: {
      name: { type: "string", required: true, search: true },
      description: { type: "string", search: true },
      is_active: { type: "boolean" },
      state: { type: "string" },
      ref: { type: "string", search: true },
      search_field: { type: "string", search: true },
      created_by: { type: "string" },
      custom_data: { type: "json" },
      payload: { type: "json" },
      folio_interno: { type: "string", search: true },
      fecha: { type: "string", search: true },
      contacto: { type: "string", search: true },
      contacto_id: { type: "string", search: true },
      usuario: { type: "string", search: true },
      estado: { type: "string", search: true },
      total: { type: "string", search: true },
      iva: { type: "string", search: true },
      importe: { type: "number" },
      folio: { type: "string", search: true },
      assigned_employee: { type: "string", search: true },
      init_time: { type: "string", search: true },
      end_time: { type: "string", search: true },
      sincronizado: { type: "boolean" },
      invoice_request_id: { type: "string", search: true },
      invoice_request_name: { type: "string", search: true },
      invoice_request_estado: { type: "string", search: true },
      invoice_request_monto_total: { type: "string", search: true },
      invoice_request_actualizado: { type: "string", search: true },
      ruta: { type: "string", search: true },
      cantidad: { type: "number" },
      cantidad_surtida: { type: "number" },
      precio: { type: "number" },
      product: { type: "string", search: true },
      price_origin: { type: "string", search: true },
      listaDePreciosId: { type: "string", search: true },
      offline_uuid: { type: "string", search: true },
    },
    options_map: { value: "id", label: "name" },
  }),
  tables: pedidos_tables,
  pages: pedidos_pages,
  menu: [],
});
