import type { KirletTableDecl } from "@opus-perpetuus/imperium-core-kit";

export const supplier_invoice_tables: KirletTableDecl[] = [
  {
    name: "supplier_invoice",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "name", type: "text", notNull: true },
      { name: "description", type: "text" },
      { name: "is_active", type: "boolean", notNull: true, default: true },
      { name: "state", type: "text" },
      { name: "ref", type: "text", unique: true },
      { name: "search_field", type: "text" },
      { name: "created_by", type: "text" },
      { name: "custom_data", type: "json" },
      { name: "payload", type: "json" },
      { name: "created_at", type: "text", notNull: true },
      { name: "updated_at", type: "text", notNull: true },
      { name: "folio", type: "real" },
      { name: "purchase_order", type: "text" },
      { name: "purchase_order_folio", type: "text" },
      { name: "proveedor", type: "text" },
      { name: "proveedor_nombre", type: "text" },
      { name: "proveedor_rfc", type: "text" },
      { name: "emisor_rfc", type: "text" },
      { name: "numero_factura", type: "text" },
      { name: "uuid", type: "text" },
      { name: "fecha_factura", type: "text" },
      { name: "fecha_vencimiento", type: "text" },
      { name: "subtotal", type: "real" },
      { name: "impuestos", type: "real" },
      { name: "total", type: "real" },
      { name: "origen", type: "text" },
      { name: "articulos", type: "json" },
      { name: "estado", type: "text" },
      { name: "estado_match", type: "text" },
      { name: "match_detalle", type: "json" },
      { name: "autorizado_por", type: "text" },
      { name: "motivo_autorizacion", type: "text" },
      { name: "estado_pago", type: "text" },
      { name: "monto_pagado", type: "real" },
      { name: "saldo", type: "real" },
    ],
    indexes: [
      { name: "idx_supplier_invoice_name", columns: ["name"] },
      { name: "idx_supplier_invoice_active", columns: ["is_active"] },
      { name: "idx_supplier_invoice_po", columns: ["purchase_order"] },
    ],
  },
];
