import { define_crud, define_module } from "@opus-perpetuus/imperium-core-kit";
import { supplier_invoice_pages } from "./supplier-invoice.pages.ts";
import { supplier_invoice_tables } from "./supplier-invoice.tables.ts";

export const supplier_invoice_module = define_module({
  resource: "supplier-invoice",
  labels: {
    singular: "Factura de proveedor",
    plural: "Facturas de proveedor",
    read: "Ver Facturas de proveedor",
    write: "Editar Facturas de proveedor",
  },
  routes: define_crud({
    resource: "supplier-invoice",
    table: "supplier_invoice",
    soft_delete: true,
    soft_delete_field: "is_active",
    history: true,
    default_sort: "name:asc",
    id_prefix: "factprov",
    fields: {
      name: { type: "string", required: true, search: true },
      description: { type: "string", search: true },
      is_active: { type: "boolean" },
      state: { type: "string" },
      ref: { type: "string", search: true },
      search_field: { type: "string", search: true },
      created_by: { type: "string" },
      custom_data: { type: "json" },
      payload: { type: "json" },
      folio: { type: "number" },
      purchase_order: { type: "string", search: true },
      purchase_order_folio: { type: "string", search: true },
      proveedor: { type: "string", search: true },
      proveedor_nombre: { type: "string", search: true },
      proveedor_rfc: { type: "string", search: true },
      emisor_rfc: { type: "string", search: true },
      numero_factura: { type: "string", search: true },
      uuid: { type: "string", search: true },
      fecha_factura: { type: "string", search: true },
      fecha_vencimiento: { type: "string", search: true },
      subtotal: { type: "number" },
      impuestos: { type: "number" },
      total: { type: "number" },
      origen: { type: "string", search: true },
      articulos: { type: "json" },
      estado: { type: "string", search: true },
      estado_match: { type: "string", search: true },
      match_detalle: { type: "json" },
      autorizado_por: { type: "string", search: true },
      motivo_autorizacion: { type: "string", search: true },
      estado_pago: { type: "string", search: true },
      monto_pagado: { type: "number" },
      saldo: { type: "number" },
    },
    options_map: { value: "id", label: "name" },
  }),
  tables: supplier_invoice_tables,
  pages: supplier_invoice_pages,
  menu: [],
});
